// config.h is autogenerated, do not change!
// config.h.cmake is its template

#ifndef CONFIG_H_CMAKE
#define CONFIG_H_CMAKE

#cmakedefine _ENABLE_PHOEBUS
#cmakedefine WIN32
#cmakedefine IS64BIT
#ifdef WIN32
#ifdef IS64BIT
#define _MINGW64BIT
#else
#define _MINGW32BIT
#endif // endif is64bit
#else // unix time
#ifdef IS64BIT
#define _LINUX64BIT
#else
#define _LINUX32BIT
#endif // endif is64bit
#endif // endif win32


#endif // guard block
