
//*** Do not edit ****
//*** Automatically generated by make_version ***
 
char *vstr = "ibp_client: v1.0.3p0\n"
             "Build Date: Tue Mar 24 15:17:01 CDT 2009\n"
             "Compiler: gcc (GCC) 4.2.4 (Ubuntu 4.2.4-1ubuntu3)\n"
             "Compile flags: -I. -I/workspace/local/include -I/workspace/local/include/glib-2.0 -g -fPIC -Wall -I -I. -D_LINUX64BIT -D_ENABLE_PHOEBUS -DHAVE_STDINT_H -D_ENABLE_DEBUG -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -O2\n"
             "Build Host: alandepot1.reddnet.org\n"
             "Build OS: 2.6.24-23-server #1 SMP Thu Nov 27 18:45:02 UTC 2008 x86_64\n";        

char *ibp_client_version() {
    return(vstr);
}

