
//*** Do not edit ****
//*** Automatically generated by make_version ***
 
char *vstr = "ibp_client: v1.0.3p0\n"
             "Build Date: Thu Jul 30 17:30:41 CDT 2009\n"
             "Compiler: gcc (GCC) 4.2.4 (Ubuntu 4.2.4-1ubuntu4)\n"
             "Compile flags: -I. -I/workspace/local/include -I/workspace/local/include/apr-1 -g -fPIC -Wall -I -I. -D_LINUX64BIT -D_ENABLE_DEBUG -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -O2\n"
             "Build Host: alandepot1.reddnet.org\n"
             "Build OS: 2.6.24-24-server #1 SMP Wed Apr 15 15:41:09 UTC 2009 x86_64\n";        

char *ibp_client_version() {
    return(vstr);
}

